"model_configuration":
    "decoder_layers": 6
    "attention_heads": 8
    "d_model": 512
    "ff_dim": 2048
    "dropout": 0.1
"image_specs": 
    "img_feature_channels": 1280
"embedding":
    "size": 512
    "embedding_dim": 512

"vocab_size": None
"max_len": 100
"mixed_precision": True
"gradient_clip": 5
"img_size": 400
# "img_dir": "/data/jaeyeong/KMolOCR_renew/data/images"
# "smiles_dir": "/data/jaeyeong/KMolOCR_renew/data/smiles_cleansed"
# "vocab_dir": "/data/jaeyeong/KMolOCR_renew/data/TOKENMAP_seed_3609_max200smiles.json"
"img_dir": "/mount/images"
"smiles_dir": "/mount/smiles_cleansed"
"vocab_dir": "/mount/TOKENMAP_seed_3609_max200smiles.json"

"test": False
"batch_size": 28
"num_workers": 32
"device": "cuda"
"lr": 0.001
"weight_decay": 0.000001
"num_epochs": 10
"seed": 42

'decoder_lr_factor': 10
"scheduler": "CosineAnnealingWarmUpRestarts"

# cosine annealing
"T_max": 10000
"eta_min": 0

# cosine annealing warmup restart
"T_0": 10000
"T_mult": 2
"eta_max": 0.001
"T_up": 50
"gamma": 0.9

"state_dict_dir": "/mount/KMolOCR/2024-02-03_13_43_42/1_2.pt"
"load_optimizer": False
"eval_first": False

# utils
# overall debugging