wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1706954360.860985
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 17
      - 23
      - 37
      4: 3.10.8
      5: 0.16.2
      8:
      - 5
      10:
      - 3
      13: linux-x86_64
model_configuration:
  desc: null
  value:
    decoder_layers: 6
    attention_heads: 8
    d_model: 512
    ff_dim: 2048
    dropout: 0.1
image_specs:
  desc: null
  value:
    img_feature_channels: 1280
embedding:
  desc: null
  value:
    size: 512
    embedding_dim: 512
vocab_size:
  desc: null
  value: None
max_len:
  desc: null
  value: 100
mixed_precision:
  desc: null
  value: true
gradient_clip:
  desc: null
  value: 5
img_size:
  desc: null
  value: 480
img_dir:
  desc: null
  value: /mount/images
smiles_dir:
  desc: null
  value: /mount/smiles_cleansed
vocab_dir:
  desc: null
  value: /mount/TOKENMAP_seed_3609_max200smiles.json
test:
  desc: null
  value: 2000
batch_size:
  desc: null
  value: 24
num_workers:
  desc: null
  value: 32
device:
  desc: null
  value: cuda
lr:
  desc: null
  value: 0.001
weight_decay:
  desc: null
  value: 1.0e-06
num_epochs:
  desc: null
  value: 10
seed:
  desc: null
  value: 42
T_max:
  desc: null
  value: 1000
eta_min:
  desc: null
  value: 0
T_0:
  desc: null
  value: 1000
T_mult:
  desc: null
  value: 2
eta_max:
  desc: null
  value: 0.003
T_up:
  desc: null
  value: 50
gamma:
  desc: null
  value: 0.7
save_dir:
  desc: null
  value: ./2024-02-03_9_59_42
SOS_idx:
  desc: null
  value: 41
PAD_idx:
  desc: null
  value: 0
EOS_idx:
  desc: null
  value: 42
UNK_idx:
  desc: null
  value: 40
